### ISSUE TITLE
bad data transformation approach

### ISSUE THREAD

**Issue by vitaly-t** [XYOracleNetwork/sdk-dache-nodejs#3]
https://github.com/XYOracleNetwork/sdk-dache-nodejs/blob/c505efce88ecce056530a09473c8d7148c29079c/adapters/storage/PostgresStorage.js#L98

See: https://coderwall.com/p/irklcq/pg-promise-and-case-sensitivity-in-column-names

**Comment by arietrouw** [comment]
Stale

**Comment by vitaly-t** [comment]
@arietrouw Stale due to non-response? LOL. The issue is still there :smile:
